// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_soc.h for the primary calling header

#ifndef VERILATED_VTB_SOC___024ROOT_H_
#define VERILATED_VTB_SOC___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vtb_soc__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtb_soc___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_soc__DOT__clk;
        CData/*0:0*/ tb_soc__DOT__resetn;
        CData/*0:0*/ tb_soc__DOT__awvalid;
        CData/*0:0*/ tb_soc__DOT__wvalid;
        CData/*0:0*/ tb_soc__DOT__bready;
        CData/*0:0*/ tb_soc__DOT__arvalid;
        CData/*0:0*/ tb_soc__DOT__rready;
        CData/*0:0*/ tb_soc__DOT__trap;
        CData/*0:0*/ tb_soc__DOT__t_awready;
        CData/*0:0*/ tb_soc__DOT__t_wready;
        CData/*0:0*/ tb_soc__DOT__t_bvalid;
        CData/*0:0*/ tb_soc__DOT__t_arready;
        CData/*0:0*/ tb_soc__DOT__t_rvalid;
        CData/*0:0*/ tb_soc__DOT__b_wready;
        CData/*0:0*/ tb_soc__DOT__b_arready;
        CData/*0:0*/ tb_soc__DOT____Vcellinp__u_tpu__s_axi_wvalid;
        CData/*0:0*/ tb_soc__DOT____Vcellinp__u_tpu__s_axi_awvalid;
        CData/*0:0*/ tb_soc__DOT__bb_valid;
        CData/*0:0*/ tb_soc__DOT__rb_valid;
        CData/*1:0*/ tb_soc__DOT__wr_st;
        CData/*2:0*/ tb_soc__DOT__rd_st;
        CData/*0:0*/ tb_soc__DOT__b_aw_fire;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__pcpi_valid;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__mem_valid;
        CData/*3:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__mem_wstrb;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__mem_ready;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__axi_adapter__DOT__ack_awvalid;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__axi_adapter__DOT__ack_arvalid;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__axi_adapter__DOT__ack_wvalid;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__axi_adapter__DOT__xfer_done;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_la_read;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_la_write;
        CData/*3:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_la_wstrb;
        CData/*4:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__reg_sh;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__pcpi_div_wr;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__pcpi_div_wait;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__pcpi_div_ready;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__pcpi_int_wr;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__pcpi_int_ready;
        CData/*1:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_state;
        CData/*1:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_wordsize;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_do_prefetch;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_do_rinst;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_do_rdata;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_do_wdata;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_xfer;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_done;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_lui;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_auipc;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_jal;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_jalr;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_beq;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_bne;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_blt;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_bge;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_bltu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_bgeu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_lb;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_lh;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_lw;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_lbu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_lhu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sb;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sh;
    };
    struct {
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sw;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_addi;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_slti;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sltiu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_xori;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_ori;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_andi;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_slli;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_srli;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_srai;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_add;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sub;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sll;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_slt;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sltu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_xor;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_srl;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_sra;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_or;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_and;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_rdcycle;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_rdcycleh;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_rdinstr;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_rdinstrh;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_ecall_ebreak;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_fence;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_getq;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_setq;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_retirq;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_maskirq;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_waitirq;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_timer;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__instr_trap;
        CData/*4:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__decoded_rd;
        CData/*4:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__decoded_rs1;
        CData/*4:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__decoded_rs2;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__decoder_trigger;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__decoder_pseudo_trigger;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__compressed_instr;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_lui_auipc_jal;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_lb_lh_lw_lbu_lhu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_slli_srli_srai;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_sb_sh_sw;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_lui_auipc_jal_jalr_addi_add_sub;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_slti_blt_slt;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_sltiu_bltu_sltu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_beq_bne_blt_bge_bltu_bgeu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_lbu_lhu_lw;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_alu_reg_imm;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_alu_reg_reg;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_compare;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__is_rdcycle_rdcycleh_rdinstr_rdinstrh;
        CData/*7:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__cpu_state;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__latched_store;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__latched_stalu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__latched_branch;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__latched_compr;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__latched_is_lu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__latched_is_lh;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__latched_is_lb;
        CData/*4:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__latched_rd;
        CData/*3:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__pcpi_timeout_counter;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__pcpi_timeout;
    };
    struct {
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__do_waitirq;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__alu_out_0;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__cpuregs_write;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mul;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mulh;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__instr_mulhsu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__instr_any_mulh;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__shift_out;
        CData/*3:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__active;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__pcpi_insn_valid;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__instr_div;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__instr_divu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__instr_rem;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__instr_remu;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__pcpi_wait_q;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__start;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__running;
        CData/*0:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__outsign;
        CData/*1:0*/ tb_soc__DOT__u_tpu__DOT__post_mode;
        CData/*3:0*/ tb_soc__DOT__u_tpu__DOT__post_shift;
        CData/*2:0*/ tb_soc__DOT__u_tpu__DOT__post_colsel;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__busy;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__done;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__aw_got;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__w_got;
        CData/*3:0*/ tb_soc__DOT__u_tpu__DOT__wstrb_r;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__wr_commit;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__wr_regs;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__wr_ibuf;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__start_pulse;
        CData/*1:0*/ tb_soc__DOT__u_tpu__DOT__r_state;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__obuf_we;
        CData/*2:0*/ tb_soc__DOT__u_tpu__DOT__state;
        CData/*6:0*/ tb_soc__DOT__u_tpu__DOT__tiles_row;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__f_run;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__fetch_go;
        CData/*3:0*/ tb_soc__DOT__u_tpu__DOT__fi;
        CData/*1:0*/ tb_soc__DOT__u_tpu__DOT__cap_r;
        CData/*1:0*/ tb_soc__DOT__u_tpu__DOT__cap_w;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__cap_v;
        CData/*6:0*/ tb_soc__DOT__u_tpu__DOT__f_tilex;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__f_sel;
        CData/*4:0*/ tb_soc__DOT__u_tpu__DOT__t_cnt;
        CData/*1:0*/ tb_soc__DOT__u_tpu__DOT__dr;
        CData/*1:0*/ tb_soc__DOT__u_tpu__DOT__dc;
        CData/*3:0*/ tb_soc__DOT__u_tpu__DOT__d_i;
        CData/*0:0*/ tb_soc__DOT__u_tpu__DOT__arr_clear;
        CData/*2:0*/ tb_soc__DOT__u_tpu__DOT__d_pix;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__px;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT____Vlvbound_hbfea1c97__0;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT____Vlvbound_h2689cd83__0;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
    };
    struct {
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__b_out;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vlvbound_ha4328a29__1;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vlvbound_h18adc700__1;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vlvbound_h56a04835__1;
        CData/*7:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vlvbound_h7a8acaf2__1;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__tb_soc__DOT__clk__0;
        CData/*0:0*/ __VactContinue;
        SData/*9:0*/ tb_soc__DOT__u_tpu__DOT__img_w;
        SData/*9:0*/ tb_soc__DOT__u_tpu__DOT__img_h;
        SData/*13:0*/ tb_soc__DOT__u_tpu__DOT__ibuf_a_addr;
        SData/*13:0*/ tb_soc__DOT__u_tpu__DOT__obuf_waddr;
        SData/*9:0*/ tb_soc__DOT__u_tpu__DOT__out_rows;
        SData/*13:0*/ tb_soc__DOT__u_tpu__DOT__out_wa;
    };
    struct {
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__a_out;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__a_out;
    };
    struct {
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vlvbound_hef02eede__1;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vlvbound_h45a418e9__1;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vlvbound_h263d9ac9__1;
        SData/*8:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vlvbound_h3e5db997__1;
        IData/*31:0*/ tb_soc__DOT__rdata;
        IData/*31:0*/ tb_soc__DOT__t_rdata;
        IData/*31:0*/ tb_soc__DOT__b_rdata;
        IData/*31:0*/ tb_soc__DOT__raddr_l;
        IData/*31:0*/ tb_soc__DOT__sim_ptr;
        IData/*31:0*/ tb_soc__DOT__dump_and_finish__Vstatic__i;
        IData/*31:0*/ tb_soc__DOT__dump_and_finish__Vstatic__f1;
        IData/*31:0*/ tb_soc__DOT__dump_and_finish__Vstatic__f2;
        IData/*31:0*/ tb_soc__DOT__dump_and_finish__Vstatic__w;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__pcpi_insn;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__mem_addr;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__mem_wdata;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_la_wdata;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__reg_pc;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__reg_next_pc;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__reg_op1;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__reg_op2;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__reg_out;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__next_pc;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__timer;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__pcpi_div_rd;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__pcpi_int_rd;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_rdata_word;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_rdata_q;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__mem_rdata_latched;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__decoded_imm;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__decoded_imm_j;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__current_pc;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__alu_out;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__alu_out_q;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__cpuregs_wrdata;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__cpuregs_rs1;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__cpuregs_rs2;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__dividend;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__quotient;
        IData/*31:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__quotient_msk;
        IData/*31:0*/ tb_soc__DOT__u_tpu__DOT__cycles;
        IData/*17:0*/ tb_soc__DOT__u_tpu__DOT__awaddr_r;
        IData/*31:0*/ tb_soc__DOT__u_tpu__DOT__wdata_r;
        IData/*17:0*/ tb_soc__DOT__u_tpu__DOT__raddr_r;
        IData/*31:0*/ tb_soc__DOT__u_tpu__DOT__reg_rdata;
        IData/*31:0*/ tb_soc__DOT__u_tpu__DOT__ibuf_a_q;
        IData/*31:0*/ tb_soc__DOT__u_tpu__DOT__ibuf_b_q;
        IData/*31:0*/ tb_soc__DOT__u_tpu__DOT__obuf_a_q;
        IData/*31:0*/ tb_soc__DOT__u_tpu__DOT__obuf_wdata;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__ntiles;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__tile_cnt;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__f_cnt;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__f_rb0;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__f_rb1;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__f_rb2;
        IData/*23:0*/ tb_soc__DOT__u_tpu__DOT__word_r;
        VlWide<3>/*71:0*/ tb_soc__DOT__u_tpu__DOT__a_flat;
        VlWide<40>/*1279:0*/ tb_soc__DOT__u_tpu__DOT__acc_flat;
        VlWide<3>/*71:0*/ tb_soc__DOT__u_tpu__DOT__a_flat_r;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__c0_r;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__c1_r;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__cs_r;
        IData/*31:0*/ tb_soc__DOT__u_tpu__DOT____Vlvbound_h9d130896__0;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc;
    };
    struct {
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__0__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__1__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__2__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__3__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__4__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__5__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__6__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__acc;
        IData/*19:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT____Vcellout__g_row__BRA__7__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__acc;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__prod;
    };
    struct {
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__0__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__1__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__2__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__3__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__4__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__5__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__6__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__0__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__1__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__2__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__3__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__4__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__5__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__6__KET____DOT__u_pe__DOT__prod;
        IData/*16:0*/ tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_row__BRA__7__KET____DOT__g_col__BRA__7__KET____DOT__u_pe__DOT__prod;
        IData/*31:0*/ __VactIterCount;
    };
    struct {
        QData/*63:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__count_cycle;
        QData/*63:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__count_instr;
        QData/*32:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__rs1;
        QData/*32:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__rs2;
        QData/*63:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk1__DOT__pcpi_mul__DOT__rd;
        QData/*62:0*/ tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__genblk2__DOT__pcpi_div__DOT__divisor;
        QData/*63:0*/ tb_soc__DOT__u_tpu__DOT__b_flat;
        QData/*63:0*/ tb_soc__DOT__u_tpu__DOT__b_flat_r;
        VlUnpacked<IData/*31:0*/, 65536> tb_soc__DOT__ram;
        VlUnpacked<IData/*31:0*/, 32> tb_soc__DOT__u_cpu__DOT__u_cpu__DOT__picorv32_core__DOT__cpuregs;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 9>, 8> tb_soc__DOT__u_tpu__DOT__ker;
        VlUnpacked<IData/*31:0*/, 16384> tb_soc__DOT__u_tpu__DOT__ibuf;
        VlUnpacked<IData/*31:0*/, 16384> tb_soc__DOT__u_tpu__DOT__obuf;
        VlUnpacked<VlUnpacked<VlWide<4>/*127:0*/, 3>, 2> tb_soc__DOT__u_tpu__DOT__bank;
        VlUnpacked<VlUnpacked<CData/*1:0*/, 3>, 2> tb_soc__DOT__u_tpu__DOT__boff;
        VlUnpacked<SData/*8:0*/, 8> tb_soc__DOT__u_tpu__DOT__u_array__DOT__a_skew;
        VlUnpacked<CData/*7:0*/, 8> tb_soc__DOT__u_tpu__DOT__u_array__DOT__b_skew;
        VlUnpacked<VlUnpacked<SData/*8:0*/, 9>, 8> tb_soc__DOT__u_tpu__DOT__u_array__DOT__h;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 8>, 9> tb_soc__DOT__u_tpu__DOT__u_array__DOT__v;
        VlUnpacked<SData/*8:0*/, 1> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_askew__BRA__1__KET____DOT__g_dly__DOT__dly;
        VlUnpacked<SData/*8:0*/, 2> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_askew__BRA__2__KET____DOT__g_dly__DOT__dly;
        VlUnpacked<SData/*8:0*/, 3> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_askew__BRA__3__KET____DOT__g_dly__DOT__dly;
        VlUnpacked<SData/*8:0*/, 4> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_askew__BRA__4__KET____DOT__g_dly__DOT__dly;
        VlUnpacked<SData/*8:0*/, 5> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_askew__BRA__5__KET____DOT__g_dly__DOT__dly;
        VlUnpacked<SData/*8:0*/, 6> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_askew__BRA__6__KET____DOT__g_dly__DOT__dly;
        VlUnpacked<SData/*8:0*/, 7> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_askew__BRA__7__KET____DOT__g_dly__DOT__dly;
        VlUnpacked<CData/*7:0*/, 1> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_bskew__BRA__1__KET____DOT__g_dly__DOT__dly;
        VlUnpacked<CData/*7:0*/, 2> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_bskew__BRA__2__KET____DOT__g_dly__DOT__dly;
        VlUnpacked<CData/*7:0*/, 3> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_bskew__BRA__3__KET____DOT__g_dly__DOT__dly;
        VlUnpacked<CData/*7:0*/, 4> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_bskew__BRA__4__KET____DOT__g_dly__DOT__dly;
        VlUnpacked<CData/*7:0*/, 5> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_bskew__BRA__5__KET____DOT__g_dly__DOT__dly;
        VlUnpacked<CData/*7:0*/, 6> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_bskew__BRA__6__KET____DOT__g_dly__DOT__dly;
        VlUnpacked<CData/*7:0*/, 7> tb_soc__DOT__u_tpu__DOT__u_array__DOT__g_bskew__BRA__7__KET____DOT__g_dly__DOT__dly;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h46ccec15__0;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtb_soc__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb_soc___024root(Vtb_soc__Syms* symsp, const char* v__name);
    ~Vtb_soc___024root();
    VL_UNCOPYABLE(Vtb_soc___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
