#!/usr/bin/env python3
"""Prepare an image for the board/simulation and generate golden references.

Pipeline (answers the "jpeg or bin?" question -- we send raw bytes, the
FPGA never sees JPEG):

  input.jpg (any size/color)
    -> grayscale (ITU-R 601 luma; the filter is 3x3x1 so we filter luminance)
    -> 240x240 (center-crop to square, then resize)
    -> edge-replicate pad 1px  -> 242x242 uint8
    -> out/image.bin   58,564 raw bytes, row-major (uploaded over UART)
    -> out/image.hex   one 32-bit word per line, 4 px/word LE ($readmemh, sim)
    -> out/image_c.h   C array (linked into the SIM firmware build)
    -> out/golden_int.bin/png   bit-exact expected TPU/CPU output (240x240)
    -> out/golden_float.png     sqrt-magnitude float reference (PSNR metric)

With no --image argument a synthetic test pattern is used, so the whole
flow (sim + board) works before you pick a photo.
"""

import argparse
import os

import numpy as np
from PIL import Image

import golden


def load_image(path):
    if path is None:
        print("no --image given: using synthetic test pattern")
        return golden.make_test_pattern()
    im = Image.open(path).convert("L")  # ITU-R 601 luma
    w, h = im.size
    s = min(w, h)  # center-crop to square so resize doesn't distort
    im = im.crop(((w - s) // 2, (h - s) // 2, (w + s) // 2, (h + s) // 2))
    im = im.resize((golden.W_OUT, golden.H_OUT), Image.LANCZOS)
    return np.asarray(im, dtype=np.uint8)


def write_hex32(path, data_bytes):
    """4 bytes/word little-endian -> one hex word per line for $readmemh."""
    b = np.frombuffer(data_bytes, dtype=np.uint8)
    pad = (-len(b)) % 4
    if pad:
        b = np.concatenate([b, np.zeros(pad, dtype=np.uint8)])
    words = b.reshape(-1, 4)
    with open(path, "w") as f:
        for w in words:
            f.write(f"{w[3]:02x}{w[2]:02x}{w[1]:02x}{w[0]:02x}\n")


def write_c_array(path, name, data_bytes):
    with open(path, "w") as f:
        f.write(f"// auto-generated by prepare_image.py\n")
        f.write(f"static const unsigned char {name}[{len(data_bytes)}] = {{\n")
        for i in range(0, len(data_bytes), 16):
            chunk = ",".join(str(x) for x in data_bytes[i:i + 16])
            f.write(f"  {chunk},\n")
        f.write("};\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--image", help="input photo (jpg/png/...); omit for test pattern")
    ap.add_argument("--outdir", default="out")
    ap.add_argument("--shift", type=int, default=0, help="post-op right shift")
    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)

    img = load_image(args.image)                       # 240x240 uint8
    img_pad = golden.pad_replicate(img)                # 242x242
    assert img_pad.shape == (golden.H_PAD, golden.W_PAD)

    raw = img_pad.tobytes()
    with open(f"{args.outdir}/image.bin", "wb") as f:
        f.write(raw)
    write_hex32(f"{args.outdir}/image.hex", raw)
    write_c_array(f"{args.outdir}/image_c.h", "IMAGE_PAD", raw)
    Image.fromarray(img).save(f"{args.outdir}/input.png")

    g_int = golden.sobel_golden_int(img_pad, shift=args.shift)   # exact HW spec
    g_flt = golden.sobel_reference_float(img_pad)                # quality ref
    with open(f"{args.outdir}/golden_int.bin", "wb") as f:
        f.write(g_int.tobytes())
    Image.fromarray(g_int).save(f"{args.outdir}/golden_int.png")
    Image.fromarray(g_flt.astype(np.uint8)).save(f"{args.outdir}/golden_float.png")

    p = golden.psnr(g_int, g_flt)
    print(f"input          : {'test pattern' if args.image is None else args.image}")
    print(f"image.bin      : {len(raw)} bytes ({golden.W_PAD}x{golden.H_PAD} padded uint8)")
    print(f"golden_int.bin : {g_int.size} bytes ({golden.W_OUT}x{golden.H_OUT})")
    print(f"PSNR |Gx|+|Gy| vs float sqrt-magnitude: {p:.2f} dB")


if __name__ == "__main__":
    main()
